const nodemailer = require('nodemailer');

module.exports = async (req, res) => {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { email, subject, body, gmailUser, gmailPass } = req.body;

    if (!email || !gmailUser || !gmailPass) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: gmailUser,
        pass: gmailPass,
      },
    });

    const formattedHtml = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject || 'ChiefVoice Notification'}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f4f6f8; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed; background-color: #f4f6f8;">
    <tr>
      <td align="center" style="padding: 40px 0 20px 0;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.05); border: 1px solid #eef2f6;">
          <tr>
            <td align="center" style="background: linear-gradient(135deg, #4f46e5 0%, #3b82f6 100%); padding: 35px 20px;">
              <h1 style="color: #ffffff; font-size: 24px; font-weight: 600; margin: 0; letter-spacing: 0.5px; font-family: inherit;">ChiefVoice CRM</h1>
              <p style="color: #bfdbfe; font-size: 14px; margin: 5px 0 0 0; font-family: inherit;">Your requested update is ready</p>
            </td>
          </tr>
          <tr>
            <td style="padding: 40px 30px; color: #334155; font-size: 16px; line-height: 1.6; font-family: inherit;">
              <p style="margin: 0 0 20px 0; font-size: 18px; font-weight: 600; color: #1e293b; font-family: inherit;">Hello,</p>
              <div style="background-color: #f8fafc; border-left: 4px solid #4f46e5; padding: 20px; border-radius: 0 8px 8px 0; margin-bottom: 25px;">
                <p style="margin: 0; font-size: 15px; color: #334155; font-family: inherit; white-space: pre-wrap;">${body}</p>
              </div>
              <p style="margin: 0 0 10px 0; font-size: 14px; color: #64748b; font-family: inherit;">This message was automatically generated by ChiefVoice CRM AI Assistant based on your phone call request.</p>
            </td>
          </tr>
          <tr>
            <td align="center" style="padding: 25px 30px; background-color: #f8fafc; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; font-family: inherit;">
              <p style="margin: 0 0 5px 0; font-family: inherit;">&copy; ${new Date().getFullYear()} ChiefVoice. All rights reserved.</p>
              <p style="margin: 0; font-family: inherit;">This is a transactional automated notification. Please do not reply directly to this mail.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

    await transporter.sendMail({
      from: gmailUser,
      to: email,
      subject: subject || 'Notification from ChiefVoice',
      text: body,
      html: formattedHtml
    });

    return res.status(200).json({ success: true });
  } catch (error) {
    console.error('Email send error:', error);
    return res.status(500).json({ error: error.message });
  }
};
